
.PHONY: all

all: pex_torus5_1.spr pex_torus5_2.spr pex_torus5_3.spr pex_torus5_4.spr

#pex_torus4_1.spr: pex_torus4_1.png
#	../../../util/spriteconv/convert -1 2 -2 5 -3 6 -b 0 -d 1 -o 1 pex_torus4_1.png
#pex_torus4_2.spr: pex_torus4_2.png
#	../../../util/spriteconv/convert -1 2 -2 5 -3 6 -b 0 -d 2 -o 1 pex_torus4_2.png

pex_torus5_1.spr: pex_torus5_1.png
	../../../util/spriteconv/convert -1 2 -2 5 -3 6 -b 0 -d 1 -o 1 pex_torus5_1.png
pex_torus5_2.spr: pex_torus5_2.png
	../../../util/spriteconv/convert -1 2 -2 5 -3 6 -b 0 -d 2 -o 1 pex_torus5_2.png
pex_torus5_3.spr: pex_torus5_3.png
	../../../util/spriteconv/convert -1 2 -2 5 -3 6 -b 0 -d 1 -o 1 pex_torus5_3.png
pex_torus5_4.spr: pex_torus5_4.png
	../../../util/spriteconv/convert -1 2 -2 5 -3 6 -b 0 -d 2 -o 1 pex_torus5_4.png

clean:
	-rm *.bin
