link_music_init_side1		= $1000
link_music_play_side1		= link_music_init_side1 + 3
link_music_fade_side1		= link_music_init_side1 + 6

link_music_init_side1b		= $9800
link_music_play_side1b		= link_music_init_side1b + 3
link_music_fade_side1b		= link_music_init_side1b + 6

link_music_init_side1c		= $0800
link_music_play_side1c		= link_music_init_side1c + 3
link_music_fade_side1c		= link_music_init_side1c + 6

link_music_init_side2		= $fc00
link_music_play_side2		= link_music_init_side2 + 3
link_music_fade_side2		= link_music_init_side2 + 6

link_music_init_side3		= $f200
link_music_play_side3		= link_music_init_side3 + 3
link_music_fade_side3		= link_music_init_side3 + 6

link_music_init_side3b		= $0800
link_music_play_side3b		= link_music_init_side3b + 3
link_music_fade_side3b		= link_music_init_side3b + 6

link_music_init_side4_micro	= $fc00
link_music_play_side4_micro	=  link_music_init_side4_micro + 3
